version: '3'

networks:
  broker_network:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - '2181:2181'
    networks:
      - broker_network
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: 'create-user:1:1, find-all-user:1:1, find-user:1:1'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_TOPIC_METADATA_REFRESH_INTERVAL_MS: "60000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - broker_network


  notification-engine:
    build:
      context: ./notification-engine
      dockerfile: Dockerfile.dev
    container_name: notification_engine
    command: yarn start
    environment:
        NODE_ENV: staging
    ports:
        - "3000"
    depends_on:
      - kafka
    networks:
      - broker_network

  
  book-engine:
    build:
      context: ./book-engine
      dockerfile: Dockerfile.dev
    container_name: book_engine
    command: yarn start
    environment:
        NODE_ENV: staging
    ports:
        - "3000"
    depends_on:
      - notification-engine
    networks:
      - broker_network


  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    container_name: api_gateway
    command: yarn start
    environment:
      NODE_ENV: staging
      PORT: 3000
      KEY_CLOAK_URI: http://host.docker.internal:8080/auth/realms/microservices/protocol/openid-connect/token
      KEY_CLOAK_CLIENT_ID: micro-services
      KEY_CLOAK_GRANT_TYPE: password
      KEY_CLOAK_CLIENT_SECRET: idGnniGy8Ytdkkuq2LI05ZtJi9mt5pzL
      KEY_CLOAK_REALM_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhhCzPvmEbIwwnSy0GZcbZuPpOuiQVbpkZ2omTeIUbgY+qeIMJgat9K37IAaOWa39GGy00i3p3B0FYsm1YlbuTOGcrNoc1jy029gseJr0T9AxVLmMfRIcsJ2UchaG+tdbpGzbpIiPrPMPUM58vZXo5arNF8J6gcrO9YSBpYZx0viHpnmk2ADnmF1ILEbQJi4ky8V0/nJBTjkgA62itwEYronpcHZZ/BFdqpYB0WL8W+r6So+63RyixXsfH5mVepP0B3dPNxnfrsla7TRICIdDoQe7jLQINipEbjCXA4HMpQPJbcphgN7fgj5AV2lDzOHNZtD58uosAh123xCCzhumAQIDAQAB
    ports:
      - '3000:3000'
    networks:
      - broker_network
    depends_on:
      - book-engine