version: '3'

networks:
  broker_network:
    driver: bridge

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    container_name: api_gateway
    command: yarn start
    environment:
      NODE_ENV: staging
      PORT: 3000
      KEY_CLOAK_URI: http://host.docker.internal:8080/auth/realms/microservices/protocol/openid-connect/token
      KEY_CLOAK_CLIENT_ID: micro-services
      KEY_CLOAK_GRANT_TYPE: password
      KEY_CLOAK_CLIENT_SECRET: b1gNbcnHM71tYm5XCm6B2Pl5Xhs8KIul
      KEY_CLOAK_REALM_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApkUXm0lLgPH0ktWdb/WX0hby941xoEUrrmUtonpqWSKlowVu0pq5weS0DLMz9hCWEf97PLVs2LCGlmhqgLSpF3gX5kYtYOf0LHBOGyZ/v6u2vEYXvcCKAyZzoPCJ86ap0HoOJZoNT3/67LWHGmTARWLpbCBZpxJC8xzht5KSu29fE3EOAIPo/eN7d8Rzb8bCwXriQl7/6BZSI9CnGufMyDlPWOrUS8XZc+MloTi52Fr+flKMNqw4LhxyFCxM6f98ks5itD32I7cExxSzt8kRcwugyfbmIvRUhh95chRV52jdf2EgJ0EY+ohza0pCvk/l+9Pi0j5rpVU48IINwIuY/wIDAQAB
    ports:
      - '3000:3000'
    networks:
      - broker_network