version: '3'

networks:
  broker_network:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - '2181:2181'
    networks:
      - broker_network
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: 'create-user:1:1, find-all-user:1:1, find-user:1:1'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_TOPIC_METADATA_REFRESH_INTERVAL_MS: "60000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - broker_network


  notification-engine:
    build:
      context: ./notification-engine
      dockerfile: Dockerfile.dev
    container_name: notification_engine
    command: yarn start
    environment:
        NODE_ENV: staging
    ports:
        - "3000"
    depends_on:
      - kafka
    networks:
      - broker_network

  
  book-engine:
    build:
      context: ./book-engine
      dockerfile: Dockerfile.dev
    container_name: book_engine
    command: yarn start
    environment:
        NODE_ENV: staging
    ports:
        - "3000"
    depends_on:
      - notification-engine
    networks:
      - broker_network


  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    container_name: api_gateway
    command: yarn start
    environment:
      NODE_ENV: staging
      PORT: 3000
      KEY_CLOAK_URI: http://host.docker.internal:8080/auth/realms/microservices/protocol/openid-connect/token
      KEY_CLOAK_CLIENT_ID: micro-services
      KEY_CLOAK_GRANT_TYPE: password
      KEY_CLOAK_CLIENT_SECRET: WJ7wDl3lp4qottXd2w4x8hWNHB9A6rHd
      KEY_CLOAK_REALM_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjOl1VNh3uBkRrPSiZNJEvYG1yosZdyCrj63oPzPmB1S6tgDxACpIshgOlO7yKP0khE79IYhTZjD6PmcZ0ffF6QMrMvMox2jopM2rmSw7AOybTmeFXWhncYwWSP8x5hYcij1hqIWiy5wRu8CkRhjaE2ucFEoyxCJ24zFyBe5UFa76whGN4nrteQvZCVu81gPgqUZiZU5h+R/iuSy5nFsTdkwRenRJ7/DtMmLQlk3mrmK0K0v2oWQ0RgPIqndAGcahNbx5b4udMMAqg4TBVLPOMu0bsdI6Cp7dmI+sFfW5CVKmkZ5VerumGEPhJHunNhJVqyRgfUVVrH8Ceiuzta8PDQIDAQAB
    ports:
      - '3000:3000'
    networks:
      - broker_network
    depends_on:
      - book-engine