version: '3'

networks:
  broker_network:
    driver: bridge

services:
  keycloak:
    image: jboss/keycloak:latest
    volumes:
      - ./realm-export.json:/realm-export.json
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
      - KEYCLOAK_IMPORT=/realm-export.json
    ports:
      - 8080:8080
    networks:
      - broker_network