version: '3'
services:
  user-engine:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: user_engine_stg
    command: yarn start
    environment:
      NODE_ENV: staging
    ports:
      - '3000'
    networks:
      - broker-kafka
networks:
  broker-kafka:
    driver: bridge
