name: Build | STG

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      
      - name: Copy repository
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: cd ./api-gateway && npm install
      
      - name: Lint code
        run: cd ./api-gateway && npm run lint
      
      - name: Run tests
        run: cd ./api-gateway && npm run test
      
      - name: Run tests e2e
        run: cd ./api-gateway && npm run test:e2e