name: Build and Deploy | STG

on:
  pull_request: 
    - dev
    types: [closed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      
      - name: Copy repository
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: cd api-gateway && yarn install
      
      - name: Lint code
        run: yarn lint
      
      - name: Run tests
        run: yarn test
      
      - name: Run tests e2e
        run: yarn test:e2e

      # - name: SonarCloud Scan
      #   uses: sonarsource/sonarcloud-github-action@master
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}